//! Explicit catalog registry and deterministic Markdown reference.
use crate::{Rule, RuleMeta, ThresholdSpec};
use nm_core::{Category, Confidence, DeviceFamily, RuleId, Severity};
use std::sync::LazyLock;
pub(crate) static META: LazyLock<[RuleMeta; 34]> = LazyLock::new(|| {
    [
        RuleMeta {
            id: RuleId::new("UBNT-SEC-001").unwrap(),
            title: "Vendor default credential",
            category: Category::Security,
            default_severity: Severity::Critical,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The assigned profile matches the vendor default username and password. Anyone ",
                "familiar with the device can guess these credentials. Replace them with a ",
                "unique password in a maintenance window and enter the new profile here. Scan ",
                "again and confirm this finding clears.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-002").unwrap(),
            title: "Public management address",
            category: Category::Security,
            default_severity: Severity::High,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The enrolled management address is public. Internet exposure increases the ",
                "chance of unauthorized access if upstream filtering allows it. Put management ",
                "on a private network or restrict access to trusted source addresses. Verify ",
                "the upstream access policy and management reachability from outside the ",
                "network.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-003").unwrap(),
            title: "Unencrypted web management",
            category: Category::Security,
            default_severity: Severity::High,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "HTTP management is enabled without confirmed HTTPS, or HTTPS is explicitly ",
                "disabled. HTTP sends login information without transport encryption. Enable ",
                "HTTPS and disable HTTP if the platform supports it. Verify the secure URL and ",
                "scan again.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-004").unwrap(),
            title: "Telnet enabled",
            category: Category::Security,
            default_severity: Severity::High,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "Telnet is enabled on this device. Its traffic, including passwords, travels ",
                "without encryption. Disable Telnet and use SSH for terminal access. Confirm ",
                "SSH works before disabling Telnet and verify the next scan.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-005").unwrap(),
            title: "Default SNMP community",
            category: Category::Security,
            default_severity: Severity::High,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "SNMP is enabled with the default public or private community. These ",
                "well-known values can expose monitoring data or permit writes where ",
                "configured. Replace the community and restrict SNMP to your monitoring hosts. ",
                "Verify polling with the replacement value and scan again.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-006").unwrap(),
            title: "UPnP enabled on router",
            category: Category::Security,
            default_severity: Severity::Medium,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "UPnP is enabled on a router. Clients may create inbound mappings that bypass ",
                "the intended access policy. Disable UPnP unless there is a documented ",
                "operational requirement. Check the remaining mappings and verify needed ",
                "applications still work.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-007").unwrap(),
            title: "Discovery enabled on WAN router",
            category: Category::Security,
            default_severity: Severity::Medium,
            confidence: Confidence::Heuristic,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "Discovery is enabled on a router with a WAN interface. Discovery traffic can ",
                "disclose device details if the service reaches that interface. Restrict ",
                "discovery to trusted interfaces or disable it. Confirm interface roles and ",
                "verify discovery behavior from the upstream segment.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-008").unwrap(),
            title: "Deprecated SSH algorithms required",
            category: Category::Security,
            default_severity: Severity::Medium,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "SSH collection required legacy algorithms. Older algorithms weaken the ",
                "protection of terminal sessions. Check for a supported firmware release with ",
                "modern SSH algorithms. Test modern SSH access before removing the legacy ",
                "exception.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-009").unwrap(),
            title: "SSH host key changed",
            category: Category::Security,
            default_severity: Severity::High,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The SSH host key differs from the pinned key. This may indicate replacement, ",
                "reset, or interception of the device connection. Verify the fingerprint ",
                "through a trusted independent channel. Accept a replacement key only after ",
                "confirming the device identity.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-010").unwrap(),
            title: "Firmware below bundled baseline",
            category: Category::Security,
            default_severity: Severity::Medium,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The observed firmware is older than the bundled platform baseline. Older ",
                "releases may lack fixes available in supported updates. Review the vendor ",
                "release notes and your platform compatibility before scheduling an update. ",
                "Scan after updating and verify the reported version.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-SEC-011").unwrap(),
            title: "WAN firewall missing",
            category: Category::Security,
            default_severity: Severity::High,
            confidence: Confidence::Heuristic,
            families: &[DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "An EdgeRouter WAN interface has neither an inbound nor a local firewall ",
                "attached. Forwarded traffic and traffic to the router may lack the intended ",
                "protection. Confirm the WAN role and attach suitable rules for both traffic ",
                "paths. Test management access and permitted traffic before closing the ",
                "maintenance window.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-001").unwrap(),
            title: "Radio chain imbalance",
            category: Category::RfHealth,
            default_severity: Severity::Medium,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "The radio chains differ more than the configured limit. This can indicate ",
                "alignment, polarization, cabling, or antenna problems. Inspect the ",
                "installation and align the link while watching each chain. Confirm the chain ",
                "values converge and repeat the measurement.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "imbalance_db",
                default: toml::Value::Integer(6),
                description: "Maximum allowed chain RSSI difference in dB.",
            }],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-002").unwrap(),
            title: "Low CCQ",
            category: Category::RfHealth,
            default_severity: Severity::Medium,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "The observed CCQ is below the configured minimum. Retries or poor radio ",
                "conditions may reduce useful capacity. Review alignment, signal and ",
                "interference before changing settings. Repeat measurements under ",
                "representative traffic because one snapshot cannot establish persistence.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "ccq_pct",
                default: toml::Value::Integer(70),
                description: "Minimum observed CCQ percentage.",
            }],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-003").unwrap(),
            title: "High sector airtime",
            category: Category::RfHealth,
            default_severity: Severity::High,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "The sector reports high busy airtime. This may limit new traffic and increase ",
                "latency. Inspect interference and station efficiency, then consider channel ",
                "planning or moving load. Repeat measurements during busy periods to confirm ",
                "the effect of changes.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "airtime_pct",
                default: toml::Value::Integer(80),
                description: "Maximum busy airtime percentage.",
            }],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-004").unwrap(),
            title: "Weak station signal",
            category: Category::RfHealth,
            default_severity: Severity::Medium,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "A station reports signal below the configured minimum. A weak link may fall ",
                "to lower rates or lose packets. Check line of sight, antenna alignment and ",
                "expected distance. Verify signal on both ends after correcting the ",
                "installation.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "signal_dbm",
                default: toml::Value::Integer(-75),
                description: "Minimum acceptable station RSSI in dBm.",
            }],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-005").unwrap(),
            title: "High sector noise floor",
            category: Category::RfHealth,
            default_severity: Severity::Medium,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "The sector reports a high noise floor. Interference can reduce the signal ",
                "margin and usable radio rates. Survey the spectrum and review channel reuse ",
                "at the site. Compare noise and link quality before and after a planned ",
                "channel change.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "noise_dbm",
                default: toml::Value::Integer(-90),
                description: "Maximum acceptable sector noise floor in dBm.",
            }],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-006").unwrap(),
            title: "Overlapping sector channels",
            category: Category::RfHealth,
            default_severity: Severity::Medium,
            confidence: Confidence::Heuristic,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "Two AP sectors assigned to the same site have overlapping channel ranges. ",
                "Nearby sectors may interfere, but site labels alone do not establish physical ",
                "separation. Confirm their positions and review the channel plan. Recheck the ",
                "overlap and radio quality after a coordinated change.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-007").unwrap(),
            title: "Low modulation for observed signal",
            category: Category::RfHealth,
            default_severity: Severity::Low,
            confidence: Confidence::Heuristic,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "The observed MCS is more than two steps below the signal expectation table ",
                "for this channel width. Noise, retries or equipment differences may explain ",
                "the gap. Review both ends of the link and interference before changing power ",
                "or width. Confirm modulation improves under comparable load.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-008").unwrap(),
            title: "Wide channel with low observed traffic",
            category: Category::RfHealth,
            default_severity: Severity::Info,
            confidence: Confidence::Heuristic,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "The channel is wide while measured traffic is low. A narrower channel may ",
                "improve reuse and noise tolerance if peak demand permits it. Review peak ",
                "traffic history before changing the width. Measure busy-hour throughput and ",
                "latency after any change.",
            ),
            thresholds: vec![
                ThresholdSpec {
                    key: "wide_mhz",
                    default: toml::Value::Integer(40),
                    description: "Channel width above which utilization is reviewed.",
                },
                ThresholdSpec {
                    key: "throughput_mbps",
                    default: toml::Value::Integer(10),
                    description: "Observed traffic ceiling for a channel width review.",
                },
            ],
        },
        RuleMeta {
            id: RuleId::new("UBNT-RF-009").unwrap(),
            title: "Distance exceeds site limit",
            category: Category::RfHealth,
            default_severity: Severity::Low,
            confidence: Confidence::Heuristic,
            families: &[DeviceFamily::AirOs],
            explanation_md: concat!(
                "A station reports a distance beyond the site maximum entered by the operator. ",
                "This may mean the wrong sector assignment or an inaccurate distance ",
                "observation. Confirm the actual location and the site limit. Correct the site ",
                "record or installation and verify the next scan.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-PERF-001").unwrap(),
            title: "Hardware offload disabled",
            category: Category::Performance,
            default_severity: Severity::High,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "IPv4 forwarding offload is disabled on a model with hardware offload. ",
                "Forwarding may consume more CPU and reduce routing throughput. Check feature ",
                "compatibility before enabling offload in a maintenance window. Verify offload ",
                "status and CPU use under representative traffic.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("UBNT-PERF-002").unwrap(),
            title: "Load exceeds CPU capacity",
            category: Category::Performance,
            default_severity: Severity::Medium,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The one-minute load exceeds the CPU count times the configured factor. Queued ",
                "work may increase latency or slow management operations. Review traffic, ",
                "enabled features and offload status. Repeat the measurement to establish ",
                "persistence before changing capacity.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "load_factor",
                default: toml::Value::Float(1.0),
                description: "Maximum one-minute load divided by CPU count.",
            }],
        },
        RuleMeta {
            id: RuleId::new("UBNT-PERF-003").unwrap(),
            title: "Low available memory",
            category: Category::Performance,
            default_severity: Severity::Medium,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "Available memory is below the configured minimum. Memory pressure can disrupt ",
                "services or collection. Review running features and investigate unexpected ",
                "consumption. Repeat the measurement after correcting the cause and avoid ",
                "rebooting solely on one reading.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "memory_pct",
                default: toml::Value::Integer(10),
                description: "Minimum available memory percentage.",
            }],
        },
        RuleMeta {
            id: RuleId::new("GEN-REL-002").unwrap(),
            title: "Unexpected ethernet negotiation",
            category: Category::Reliability,
            default_severity: Severity::Medium,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "An interface negotiated half duplex or a slow link to an identified ",
                "gigabit-capable peer. Cabling or mismatched negotiation settings may limit ",
                "throughput and cause errors. Inspect the cable and verify both ends use ",
                "compatible negotiation. Confirm full duplex and the expected speed after ",
                "correcting the link.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("GEN-REL-003").unwrap(),
            title: "OSPF neighbor not Full",
            category: Category::Reliability,
            default_severity: Severity::High,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "An observed OSPF neighbor is not Full. Some 2-Way neighbors on broadcast ",
                "networks are normal, so review the interface role before treating this as a ",
                "fault. For an expected full adjacency, compare timers, area, authentication ",
                "and MTU. Verify the neighbor state and learned routes after correcting a ",
                "mismatch.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("GEN-REL-004").unwrap(),
            title: "BGP peer not Established",
            category: Category::Reliability,
            default_severity: Severity::Medium,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "An observed BGP peer is not Established. Expected routes may be unavailable ",
                "until the session is restored. Check reachability, AS numbers, authentication ",
                "and the peer configuration. Verify Established state and received prefixes ",
                "after correcting the cause.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("GEN-REL-005").unwrap(),
            title: "Recent device restart",
            category: Category::Reliability,
            default_severity: Severity::Low,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The device uptime is below the configured minimum. A recent restart may be ",
                "planned or may indicate power or stability problems. Compare the restart with ",
                "maintenance records and power events. Verify uptime increases normally and ",
                "investigate repeated resets.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "uptime_seconds",
                default: toml::Value::Integer(86400),
                description: "Minimum uptime before the recent-restart finding clears.",
            }],
        },
        RuleMeta {
            id: RuleId::new("GEN-CAP-001").unwrap(),
            title: "DHCP pool nearly exhausted",
            category: Category::Capacity,
            default_severity: Severity::Medium,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The DHCP pool utilization exceeds the configured limit. New clients may fail ",
                "to obtain an address if the pool fills. Review lease duration and address ",
                "usage before expanding the pool. Verify available addresses and successful ",
                "client leases after making a planned change.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "pool_ratio",
                default: toml::Value::Float(0.9),
                description: "Maximum fraction of pool addresses leased.",
            }],
        },
        RuleMeta {
            id: RuleId::new("GEN-CAP-002").unwrap(),
            title: "High sector station count",
            category: Category::Capacity,
            default_severity: Severity::Medium,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The sector station count exceeds the configured planning limit. Airtime ",
                "demand depends on traffic and radio efficiency as well as device count. ",
                "Review the model, busy-hour utilization and client mix, then tune this ",
                "threshold. Verify airtime and latency before deciding to split the sector.",
            ),
            thresholds: vec![ThresholdSpec {
                key: "max_stations",
                default: toml::Value::Integer(60),
                description: "Operator-adjustable maximum stations per AP sector.",
            }],
        },
        RuleMeta {
            id: RuleId::new("GEN-HYG-001").unwrap(),
            title: "Firmware differs among site peers",
            category: Category::Hygiene,
            default_severity: Severity::Low,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "Devices of the same model at this site run different firmware versions. ",
                "Differences can complicate support and introduce inconsistent behavior. ",
                "Review release notes and choose a tested version for the model. Verify the ",
                "site versions after a coordinated maintenance update.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("GEN-HYG-002").unwrap(),
            title: "Factory default hostname",
            category: Category::Hygiene,
            default_severity: Severity::Low,
            confidence: Confidence::Likely,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The hostname matches a common factory default. Ambiguous names make ",
                "troubleshooting and device identification harder. Choose a unique name that ",
                "reflects the device role and site. Verify the new name appears in the next ",
                "scan.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("GEN-HYG-003").unwrap(),
            title: "No NTP configured",
            category: Category::Hygiene,
            default_severity: Severity::Info,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "The collected configuration lists no NTP servers. Unsynchronized clocks make ",
                "logs and event correlation less reliable. Configure reachable time servers ",
                "appropriate for the network. Check clock synchronization and the next ",
                "configuration scan.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("GEN-HYG-004").unwrap(),
            title: "Controller enrollment differs from siblings",
            category: Category::Hygiene,
            default_severity: Severity::Low,
            confidence: Confidence::Heuristic,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "A manually enrolled device shares a site and family with a device imported ",
                "from a controller. It may be missing from centralized management, although ",
                "inventory source alone is not proof. Check the controller inventory and ",
                "intended enrollment policy. Update enrollment or record the intended ",
                "exception.",
            ),
            thresholds: vec![],
        },
        RuleMeta {
            id: RuleId::new("GEN-HYG-005").unwrap(),
            title: "Incomplete collection",
            category: Category::Hygiene,
            default_severity: Severity::Info,
            confidence: Confidence::Certain,
            families: &[DeviceFamily::AirOs, DeviceFamily::EdgeOs],
            explanation_md: concat!(
                "Collection is incomplete for this device. Rules depending on missing ",
                "observations cannot evaluate those conditions reliably. Review the listed ",
                "artifacts and errors, then check reachability, permissions or firmware ",
                "support. Scan again and confirm coverage improves.",
            ),
            thresholds: vec![],
        },
    ]
});
static RULES: [crate::rules::CatalogRule; 34] = [
    crate::rules::CatalogRule(0),
    crate::rules::CatalogRule(1),
    crate::rules::CatalogRule(2),
    crate::rules::CatalogRule(3),
    crate::rules::CatalogRule(4),
    crate::rules::CatalogRule(5),
    crate::rules::CatalogRule(6),
    crate::rules::CatalogRule(7),
    crate::rules::CatalogRule(8),
    crate::rules::CatalogRule(9),
    crate::rules::CatalogRule(10),
    crate::rules::CatalogRule(11),
    crate::rules::CatalogRule(12),
    crate::rules::CatalogRule(13),
    crate::rules::CatalogRule(14),
    crate::rules::CatalogRule(15),
    crate::rules::CatalogRule(16),
    crate::rules::CatalogRule(17),
    crate::rules::CatalogRule(18),
    crate::rules::CatalogRule(19),
    crate::rules::CatalogRule(20),
    crate::rules::CatalogRule(21),
    crate::rules::CatalogRule(22),
    crate::rules::CatalogRule(23),
    crate::rules::CatalogRule(24),
    crate::rules::CatalogRule(25),
    crate::rules::CatalogRule(26),
    crate::rules::CatalogRule(27),
    crate::rules::CatalogRule(28),
    crate::rules::CatalogRule(29),
    crate::rules::CatalogRule(30),
    crate::rules::CatalogRule(31),
    crate::rules::CatalogRule(32),
    crate::rules::CatalogRule(33),
];
static REGISTRY: LazyLock<Vec<&'static dyn Rule>> =
    LazyLock::new(|| RULES.iter().map(|r| r as &dyn Rule).collect());
/// Every supported single-snapshot rule, in documented order.
pub fn all() -> &'static [&'static dyn Rule] {
    &REGISTRY
}
/// Render the catalog without timestamps so CI can detect stale documentation.
pub fn export_md() -> String {
    use std::fmt::Write;
    let mut out=String::from("# NetworkMaster rule catalog\n\nGenerated by `netmaster rules export-md`. Edit the catalog to change this reference.\n\n");
    for rule in all() {
        let m = rule.meta();
        writeln!(out,"## {} — {}\n\nSeverity: **{:?}** · Category: **{:?}** · Confidence: **{:?}**\n\nFamilies: {}\n",m.id,m.title,m.default_severity,m.category,m.confidence,m.families.iter().map(|f|format!("{f:?}")).collect::<Vec<_>>().join(", ")).unwrap();
        if !m.thresholds.is_empty() {
            out.push_str("| Threshold | Default | Meaning |\n| --- | --- | --- |\n");
            for t in &m.thresholds {
                writeln!(out, "| `{}` | `{}` | {} |", t.key, t.default, t.description).unwrap();
            }
            out.push('\n');
        }
        writeln!(out, "{}\n", m.explanation_md).unwrap();
    }
    out.trim_end().to_owned() + "\n"
}
